## https://pnpm.io/workspaces
packages:
  - 'layers/*'
  - 'plays/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  manage:
    "@changesets/cli": "2.27.11"
    "pnpm-hoist-layer": "1.2.0"
    "rimraf": "6.0.1"
    "taze": "18.2.0"
  common:
    "@pinia/nuxt": "0.9.0" # https://github.com/vuejs/pinia/blob/v2.3.0/packages/nuxt/package.json
    "@vueuse/core": "12.4.0" #https://github.com/vueuse/vueuse/blob/v12.0.0/pnpm-workspace.yaml
    "@vueuse/nuxt": "12.4.0"
    "date-fns": "4.1.0"
    "js-md5": "0.8.3"
    "nuxt-swiper": "2.0.0"
    "nuxt": "3.15.2"
    "pinia": "2.3.0" # https://github.com/vuejs/pinia/blob/v2.3.0/packages/pinia/CHANGELOG.md
    "swiper": "11.2.1" # https://github.com/cpreston321/nuxt-swiper/blob/v2.0.0/package.json
    "ulid": "2.3.0"
    "vue-router": "4.5.0" # https://github.com/nuxt/nuxt/blob/v3.15.2/packages/nuxt/package.json
    "vue": "3.5.13" # https://github.com/nuxt/nuxt/blob/v3.15.2/packages/nuxt/package.json
  commonDev:
    "@iconify-json/line-md": "1.2.5"
    "@iconify-json/mdi": "1.2.2"
    "@nuxt/eslint": "0.7.5" # https://github.com/nuxt/eslint/blob/main/pnpm-workspace.yaml check nuxt
    "@nuxt/test-utils": "3.15.4" # https://github.com/nuxt/nuxt/blob/v3.15.2/package.json
    "@unocss/core": "65.4.2" # https://github.com/unocss/unocss/blob/v65.4.2/pnpm-workspace.yaml
    "@unocss/eslint-config": "65.4.2"
    "@unocss/nuxt": "65.4.2"
    "@unocss/preset-icons": "65.4.2"
    "@unocss/preset-wind": "65.4.2"
    "@unocss/transformer-directives": "65.4.2"
    "@unocss/transformer-variant-group": "65.4.2"
    "@vitest/coverage-v8": "2.1.8"
    "@vue/test-utils": "2.4.6"
    "eslint": "9.18.0" # https://github.com/nuxt/nuxt/blob/v3.15.2/package.json
    "happy-dom": "16.6.0" # peer of @nuxt/test-utils # https://github.com/nuxt/nuxt/blob/v3.15.2/package.json
    "msw": "2.7.0" # API mocking
    "nuxi": "3.20.0" # by nuxt # https://github.com/nuxt/nuxt/blob/v3.15.2/package.json @nuxt/cli
    "typescript": "5.7.3" # https://github.com/nuxt/nuxt/blob/v3.15.2/package.json
    "unocss": "65.4.2"
    "vite": "6.0.7" # mute 'unmet peer' # https://github.com/nuxt/nuxt/blob/v3.15.2/packages/nuxt/package.json
    "vitest": "2.1.8" # https://github.com/nuxt/nuxt/blob/v3.15.2/packages/nuxt/package.json
    "vue-tsc": "2.2.0" # https://github.com/nuxt/nuxt/blob/v3.15.2/package.json
  mobile:
    "@capacitor/preferences": "6.0.3"
    "@ionic/core": "8.4.1" # by @ionic/vue, need types
    "@ionic/vue-router": "8.4.1"
    "@ionic/vue": "8.4.1"
    "@nuxtjs/ionic": "0.15.1"
    "ionicons": "7.4.0" # by @ionic/vue

