## https://pnpm.io/workspaces
packages:
  - 'layers/*'
  - 'plays/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  manage:
    "@changesets/cli": "2.27.9"
    "pnpm-hoist-layer": "1.1.9"
    "rimraf": "6.0.1"
    "taze": "0.18.0"
  common:
    "@vueuse/core": "11.2.0"
    "@vueuse/nuxt": "11.2.0"
    "pinia": "2.2.6"
    "vue": "3.5.12"
  commonDev:
    "@iconify-json/line-md": "1.2.2"
    "@iconify-json/mdi": "1.2.1"
    "@nuxt/eslint": "0.6.1"
    "@nuxt/test-utils": "3.14.4"
    "@pinia/nuxt": "0.7.0"
    "@unocss/core": "0.64.0"
    "@unocss/nuxt": "0.64.0"
    "@unocss/preset-icons": "0.64.0"
    "@unocss/preset-wind": "0.64.0"
    "@vitest/coverage-v8": "2.1.5"
    "@vue/test-utils": "2.4.6"
    "eslint": "9.14.0"
    "happy-dom": "15.11.6" # peer of @nuxt/test-utils
    "msw": "2.6.4" # API mocking
    "nuxi": "3.15.0" # by nuxt
    "nuxt": "3.14.159"
    "typescript": "5.6.3"
    "unocss": "0.64.0"
    "vite": "5.4.11" # peer
    "vitest": "2.1.5"
    "vue-tsc": "2.1.10"
  mobile:
    "@capacitor/preferences": "6.0.2"
    "@ionic/vue": "8.4.0"
    "@ionic/vue-router": "8.4.0"
    "ionicons": "7.4.0"
  mobileDev:
    "@nuxtjs/ionic": "0.15.1"

