## https://pnpm.io/workspaces
packages:
  - 'layers/*'
  - 'plays/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  manage:
    "@changesets/cli": "2.27.10"
    "pnpm-hoist-layer": "1.1.9"
    "rimraf": "6.0.1"
    "taze": "0.18.0"
  common:
    "@pinia/nuxt": "0.9.0" # https://github.com/vuejs/pinia/blob/v2/packages/nuxt/package.json
    "@vueuse/core": "12.0.0" #https://github.com/vueuse/vueuse/blob/v12.0.0/pnpm-workspace.yaml
    "@vueuse/nuxt": "12.0.0"
    "date-fns": "4.1.0"
    "js-md5": "0.8.3"
    "nuxt-swiper": "2.0.0"
    "nuxt": "3.14.1592"
    "pinia": "2.3.0" # https://github.com/vuejs/pinia/blob/v2/packages/pinia/CHANGELOG.md
    "swiper": "11.1.15" # https://github.com/cpreston321/nuxt-swiper/blob/v2.0.0/package.json
    "ulid": "2.3.0"
    "vue-router": "4.4.5" # https://github.com/nuxt/nuxt/blob/v3.14.1592/package.json
    "vue": "3.5.13" # https://github.com/nuxt/nuxt/blob/v3.14.1592/package.json
  commonDev:
    "@iconify-json/line-md": "1.2.2"
    "@iconify-json/mdi": "1.2.1"
    "@nuxt/eslint": "0.7.2" # https://github.com/nuxt/eslint/blob/main/pnpm-workspace.yaml
    "@nuxt/test-utils": "3.14.4" # https://github.com/nuxt/nuxt/blob/v3.14.1592/package.json
    "@unocss/core": "0.65.1" # https://github.com/unocss/unocss/blob/main/pnpm-workspace.yaml
    "@unocss/eslint-config": "0.65.1"
    "@unocss/nuxt": "0.65.1"
    "@unocss/preset-icons": "0.65.1"
    "@unocss/preset-wind": "0.65.1"
    "@unocss/transformer-directives": "0.65.1"
    "@unocss/transformer-variant-group": "0.65.1"
    "@vitest/coverage-v8": "2.1.8"
    "@vue/test-utils": "2.4.6"
    "eslint": "9.15.0" # https://github.com/nuxt/nuxt/blob/v3.14.1592/package.json
    "happy-dom": "15.11.7" # peer of @nuxt/test-utils # https://github.com/nuxt/nuxt/blob/v3.14.1592/package.json
    "msw": "2.6.6" # API mocking
    "nuxi": "3.15.0" # by nuxt # https://github.com/nuxt/nuxt/blob/v3.14.1592/package.json
    "typescript": "5.6.3" # by vue-tsc https://github.com/vuejs/language-tools/issues/5018
    "unocss": "0.65.1"
    "vite": "5.4.11" # mute 'unmet peer' # https://github.com/nuxt/nuxt/blob/v3.14.1592/packages/nuxt/package.json
    "vitest": "2.1.8"
    "vue-tsc": "2.1.10"
  mobile:
    "@capacitor/preferences": "6.0.3"
    "@ionic/core": "8.4.1" # by @ionic/vue, need types
    "@ionic/vue-router": "8.4.1"
    "@ionic/vue": "8.4.1"
    "@nuxtjs/ionic": "0.15.1"
    "ionicons": "7.4.0" # by @ionic/vue

