## https://pnpm.io/workspaces
packages:
  - 'layers/*'
#  - 'starts/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  common:
    ## prd
    "@vueuse/core": "11.1.0"
    "@vueuse/nuxt": "11.1.0"
    "vue": "3.5.5"
    ## dev
    ### main framework
    "nuxt": "3.13.2"
    ### code style/lint
    "@nuxt/eslint": "0.5.7"
    "eslint": "9.10.0"
    "vite-plugin-eslint2": "4.4.1"
    ### main language
    "typescript": "5.6.2"
    "vue-tsc": "2.1.6"
    ### testing
    "@nuxt/test-utils": "3.14.2"
    "@vue/test-utils": "2.4.6"
    "happy-dom": "15.7.4"
    "vitest": "2.1.1"
    ### deploy
    "@changesets/cli": "2.27.8"
    "taze": "0.16.9"
    ### unocss icon/css
    "@iconify-json/mdi": "1.2.0"
    "@unocss/core": "0.62.4"
    "@unocss/nuxt": "0.62.4"
    "@unocss/preset-icons": "0.62.4"
    "@unocss/preset-wind": "0.62.4"
    "unocss": "0.62.4"
  mobile:
    ## prd
    "@ionic/vue": "8.3.0"
    "@ionic/vue-router": "8.3.0"
    "ionicons": "7.4.0"
    ## dev
    "@nuxtjs/ionic": "0.15.1"

