packages:
  - 'layers/*'
  - 'plays/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  manage:
    "@changesets/cli": "2.29.5"
    "del-cli": "6.0.0"
    "pnpm-hoist-layer": "1.3.1"
    "taze": "19.1.0" # https://github.com/antfu-collective/taze/releases
    "semver": "7.7.2" # https://github.com/npm/node-semver/releases
  common:
    "@nuxtjs/i18n": "9.5.6" # check:nuxt | https://github.com/nuxt-modules/i18n/blob/v9.5.6/package.json
    "@pinia/nuxt": "0.11.1" # check:nuxt | https://github.com/vuejs/pinia/blob/v3.0.3/packages/nuxt/package.json
    "@sentry/nuxt": "9.44.0" # check:nuxt | https://github.com/getsentry/sentry-javascript/blob/develop/packages/nuxt/package.json
    "@vueuse/core": "13.5.0" # check:nuxt | https://github.com/vueuse/vueuse/blob/main/pnpm-workspace.yaml
    "@vueuse/nuxt": "13.5.0"
    "date-fns": "4.1.0"
    "decimal.js": "10.6.0"
    "nuxt-svgo": "4.2.4" # check:nuxt | https://github.com/cpsoinos/nuxt-svgo/blob/v4.2.4/package.json
    "nuxt-swiper": "2.0.1" # check:nuxt | https://github.com/cpreston321/nuxt-swiper/blob/v2.0.1/package.json
    "nuxt": "3.17.7"
    "pinia": "3.0.3" # https://github.com/vuejs/pinia/blob/v3.0.3/packages/pinia/CHANGELOG.md
    "swiper": "11.2.10" # check:. | https://github.com/cpreston321/nuxt-swiper/blob/v2.0.1/package.json
    "ts-md5": "2.0.1"
    "ulid": "3.0.1"
    "validator": "13.15.15" # https://github.com/validatorjs/validator.js/releases
    "vue-router": "4.5.1" # check:. | https://github.com/nuxt/nuxt/blob/v3.17.7/packages/nuxt/package.json
    "vue": "3.5.18" # check:. | https://github.com/nuxt/nuxt/blob/v3.17.7/packages/nuxt/package.json
  commonDev:
    "@iconify-json/line-md": "1.2.8"
    "@iconify-json/mdi": "1.2.3"
    "@nuxt/eslint": "1.5.2" # check:.@nuxt/eslint-config | https://github.com/nuxt/nuxt/blob/v3.17.7/package.json
    "@nuxt/test-utils": "3.19.2" # check:. | https://github.com/nuxt/nuxt/blob/v3.17.7/package.json
    "@types/validator": "13.15.2"
    "@unocss/core": "66.3.3" # https://github.com/unocss/unocss/blob/v66.3.3/pnpm-workspace.yaml
    "@unocss/eslint-config": "66.3.3"
    "@unocss/nuxt": "66.3.3"
    "@unocss/preset-icons": "66.3.3"
    "@unocss/preset-wind4": "66.3.3"
    "@unocss/transformer-directives": "66.3.3"
    "@unocss/transformer-variant-group": "66.3.3"
    "@vitest/coverage-v8": "3.2.4" # check:. | https://github.com/nuxt/nuxt/blob/v3.17.7/package.json
    "@vue/test-utils": "2.4.6"
    "eslint": "9.30.1" # check:. | https://github.com/nuxt/nuxt/blob/v3.17.7/package.json
    "happy-dom": "18.0.1"  # check:. | https://github.com/nuxt/nuxt/blob/v3.17.7/package.json
    "sass-embedded": "1.89.2"
    "typescript": "5.8.3" # https://github.com/nuxt/nuxt/blob/v3.17.7/package.json
    "unocss": "66.3.3"
    "vitest": "3.2.4" # check:. | https://github.com/nuxt/nuxt/blob/v3.17.7/package.json
    "vue-tsc": "3.0.4" # check:. | https://github.com/nuxt/nuxt/blob/v3.17.7/package.json
  desktop:
    "vuetify": "3.9.3" # https://github.com/vuetifyjs/vuetify/releases
    "vuetify-nuxt-module": "0.18.7" # check:nuxt,vuetify | https://github.com/vuetifyjs/nuxt-module/blob/v0.18.7/package.json
  mobile:
    "@capacitor/preferences": "7.0.1" # check:.@capacitor/keyboard | https://github.com/ionic-team/ionic-framework/blob/v8.7.1/core/package.json
    "@ionic/core": "8.7.1" # by @ionic/vue, need types
    "@ionic/vue-router": "8.7.1" # check:vue-router | https://github.com/ionic-team/ionic-framework/blob/v8.7.1/packages/vue-router/package.json
    "@ionic/vue": "8.7.1" # check:vue | https://github.com/ionic-team/ionic-framework/blob/v8.7.1/packages/vue/package.json
    "@nuxtjs/ionic": "1.0.0" # check:nuxt | https://github.com/nuxt-modules/ionic/blob/v1.0.0/package.json
    "ionicons": "8.0.13" # check:. | https://github.com/ionic-team/ionic-framework/blob/v8.7.1/core/package.json
