## https://pnpm.io/workspaces
packages:
  - 'layers/*'
#  - 'starts/*'

## https://pnpm.io/catalogs
catalogs:
  common:
    ## prd
    "@vueuse/core": "^11.0.3"
    "@vueuse/nuxt": "^11.0.3"
    "vue": "^3.4.38"
    ## dev
    ### main framework
    "nuxt": "^3.12.4"
    ### code style/lint
    "@nuxt/eslint": "^0.5.4"
    "eslint": "^9.9.1"
    "vite-plugin-eslint2": "^4.4.0"
    ### main language
    "typescript": "^5.5.4"
    "vue-tsc": "^2.1.6"
    ### testing
    "@nuxt/test-utils": "^3.14.2"
    "@vue/test-utils": "^2.4.6"
    "happy-dom": "^15.7.4"
    "vitest": "^2.0.5"
    ### deploy
    "@changesets/cli": "^2.27.8"
    ### unocss icon/css
    "@iconify-json/mdi": "^1.2.0"
    "@unocss/core": "^0.62.3"
    "@unocss/nuxt": "^0.62.3"
    "@unocss/preset-icons": "^0.62.3"
    "@unocss/preset-wind": "^0.62.3"
    "unocss": "^0.62.3"
  mobile:
    ## prd
    "@ionic/vue": "^8.2.7"
    "@ionic/vue-router": "^8.2.7"
    "ionicons": "^7.4.0"
    ## dev
    "@nuxtjs/ionic": "^0.15.1"

