## https://pnpm.io/workspaces
packages:
  - 'layers/*'
#  - 'starts/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  manage:
    "@changesets/cli": "2.27.9"
    "pnpm-hoist-layer": "1.1.6"
    "rimraf": "6.0.1"
    "taze": "0.17.2"
  common:
    "@vueuse/core": "11.1.0"
    "@vueuse/nuxt": "11.1.0"
    "pinia": "2.2.4"
    "vue": "3.5.12"
  commonDev:
    "@iconify-json/line-md": "1.2.2"
    "@iconify-json/mdi": "1.2.1"
    "@nuxt/eslint": "0.6.0"
    "@nuxt/test-utils": "3.14.4"
    "@pinia/nuxt": "0.5.5"
    "@unocss/core": "0.63.6"
    "@unocss/nuxt": "0.63.6"
    "@unocss/preset-icons": "0.63.6"
    "@unocss/preset-wind": "0.63.6"
    "@vitest/coverage-v8": "2.1.3"
    "@vue/test-utils": "2.4.6"
    "eslint": "9.13.0"
    "happy-dom": "15.7.4"
    "nuxt": "3.13.2"
    "typescript": "5.6.3"
    "unocss": "0.63.6"
    "vite-plugin-eslint2": "5.0.1"
    "vitest": "2.1.3"
    "vue-tsc": "2.1.6"
  mobile:
    "@capacitor/preferences": "6.0.2"
    "@ionic/vue": "8.3.3"
    "@ionic/vue-router": "8.3.3"
    "ionicons": "7.4.0"
  mobileDev:
    "@nuxtjs/ionic": "0.15.1"

