## https://pnpm.io/workspaces
packages:
  - 'layers/*'
  - 'plays/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  manage:
    "@changesets/cli": "2.29.4"
    "pnpm-hoist-layer": "1.2.0"
    "rimraf": "6.0.1"
    "taze": "19.1.0" # https://github.com/antfu-collective/taze/releases
  common:
    "@nuxtjs/i18n": "9.5.4" # nuxt@^3.17.2 | https://github.com/nuxt-modules/i18n/blob/main/package.json
    "@pinia/nuxt": "0.11.0" # nuxt@^3.15.4 | https://github.com/vuejs/pinia/blob/v3.0.2/packages/nuxt/package.json
    "@sentry/nuxt": "9.19.0" # nuxt@^3.13.2 | https://github.com/getsentry/sentry-javascript/blob/develop/packages/nuxt/package.json
    "@vueuse/core": "13.2.0" # nuxt@^3.17.3 | https://github.com/vueuse/vueuse/blob/main/pnpm-workspace.yaml
    "@vueuse/nuxt": "13.2.0"
    "date-fns": "4.1.0"
    "decimal.js": "10.5.0"
    "nuxt-svgo": "4.1.2" # nuxt@3.17.3 | https://github.com/cpsoinos/nuxt-svgo/blob/main/package.json
    "nuxt-swiper": "2.0.1" # nuxt@^3.15.4 | https://github.com/cpreston321/nuxt-swiper/blob/main/package.json
    "nuxt": "3.17.3"
    "pinia": "3.0.2" # https://github.com/vuejs/pinia/blob/v3.0.2/packages/pinia/CHANGELOG.md
    "swiper": "11.2.6" # https://github.com/cpreston321/nuxt-swiper/blob/v2.0.1/package.json
    "ts-md5": "1.3.1"
    "ulid": "3.0.0"
    "validator": "13.15.0" # https://github.com/validatorjs/validator.js/releases
    "vue-router": "4.5.1" # https://github.com/nuxt/nuxt/blob/v3.17.3/packages/nuxt/package.json
    "vue": "3.5.13" # https://github.com/nuxt/nuxt/blob/v3.17.3/packages/nuxt/package.json
  commonDev:
    "@iconify-json/line-md": "1.2.8"
    "@iconify-json/mdi": "1.2.3"
    "@nuxt/eslint": "1.3.1" # @nuxt/eslint-config | https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
    "@nuxt/test-utils": "3.18.0" # https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
    "@types/validator": "13.15.0"
    "@unocss/core": "65.5.0" # https://github.com/unocss/unocss/blob/v65.5.0/pnpm-workspace.yaml
    "@unocss/eslint-config": "65.5.0"
    "@unocss/nuxt": "65.5.0"
    "@unocss/preset-icons": "65.5.0"
    "@unocss/preset-wind": "65.5.0"
    "@unocss/transformer-directives": "65.5.0"
    "@unocss/transformer-variant-group": "65.5.0"
    "@vitest/coverage-v8": "3.1.3" # https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
    "@vue/test-utils": "2.4.6"
    "eslint": "9.26.0" # https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
    "happy-dom": "17.4.7"  # https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
    "nuxi": "3.25.1" # @nuxt/cli | https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
    "typescript": "5.8.3" # https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
    "unocss": "65.5.0"
    "vitest": "3.1.3" # https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
    "vue-tsc": "2.2.10" # https://github.com/nuxt/nuxt/blob/v3.17.3/package.json
  mobile:
    "@capacitor/preferences": "7.0.1" # https://github.com/ionic-team/ionic-framework/blob/v8.5.7/core/package.json
    "@ionic/core": "8.5.7" # by @ionic/vue, need types
    "@ionic/vue-router": "8.5.7" # https://github.com/ionic-team/ionic-framework/releases
    "@ionic/vue": "8.5.7"
    "@nuxtjs/ionic": "0.18.0" # https://github.com/nuxt-modules/ionic
    "ionicons": "7.4.0" # by @ionic/vue

