packages:
  - 'layers/*'
  - 'plays/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  manage:
    "@changesets/cli": "2.28.1"
    "pnpm-hoist-layer": "1.2.0"
    "rimraf": "6.0.1"
    "taze": "19.0.1"
  common:
    "@nuxtjs/i18n": "9.2.1" # https://github.com/nuxt-modules/i18n/blob/main/package.json
    "@pinia/nuxt": "0.10.1" # https://github.com/vuejs/pinia/blob/v3.0.0/packages/nuxt/package.json
    "@sentry/nuxt": "9.3.0" # https://github.com/getsentry/sentry-javascript/blob/develop/packages/nuxt/package.json
    "@vueuse/core": "12.7.0" #https://github.com/vueuse/vueuse/blob/v12.7.0/pnpm-workspace.yaml
    "@vueuse/nuxt": "12.7.0"
    "date-fns": "4.1.0"
    "js-md5": "0.8.3"
    "nuxt-swiper": "2.0.0"
    "nuxt": "3.15.4"
    "pinia": "3.0.1" # https://github.com/vuejs/pinia/blob/v3.0.0/packages/pinia/CHANGELOG.md
    "swiper": "11.2.4" # https://github.com/cpreston321/nuxt-swiper/blob/v2.0.0/package.json
    "ulid": "2.3.0"
    "vue-router": "4.5.0" # https://github.com/nuxt/nuxt/blob/v3.15.4/packages/nuxt/package.json
    "vue": "3.5.13" # https://github.com/nuxt/nuxt/blob/v3.15.4/packages/nuxt/package.json
  commonDev:
    "@iconify-json/line-md": "1.2.5"
    "@iconify-json/mdi": "1.2.3"
    "@nuxt/eslint": "1.0.1" # https://github.com/nuxt/eslint/blob/v1.0.1/pnpm-workspace.yaml check nuxt
    "@nuxt/test-utils": "3.15.4" # https://github.com/nuxt/nuxt/blob/v3.15.4/package.json
    "@unocss/core": "65.5.0" # https://github.com/unocss/unocss/blob/v65.5.0/pnpm-workspace.yaml
    "@unocss/eslint-config": "65.5.0"
    "@unocss/nuxt": "65.5.0"
    "@unocss/preset-icons": "65.5.0"
    "@unocss/preset-wind": "65.5.0"
    "@unocss/transformer-directives": "65.5.0"
    "@unocss/transformer-variant-group": "65.5.0"
    "@vitest/coverage-v8": "3.0.5" # same as vitest https://github.com/vitest-dev/vitest/blob/v3.0.5/packages/coverage-v8/package.json
    "@vue/test-utils": "2.4.6"
    "eslint": "9.19.0" # https://github.com/nuxt/nuxt/blob/v3.15.4/package.json
    "happy-dom": "16.7.3" # peer of @nuxt/test-utils # https://github.com/nuxt/nuxt/blob/v3.15.4/package.json
    "nuxi": "3.21.1" # by nuxt # https://github.com/nuxt/nuxt/blob/v3.15.4/package.json @nuxt/cli
    "typescript": "5.7.3" # https://github.com/nuxt/nuxt/blob/v3.15.4/package.json
    "unocss": "65.5.0"
    "vite": "6.0.11" # mute 'unmet peer' # https://github.com/nuxt/nuxt/blob/v3.15.4/packages/nuxt/package.json
    "vitest": "3.0.5" # https://github.com/nuxt/nuxt/blob/v3.15.4/packages/nuxt/package.json
    "vue-tsc": "2.2.2" # https://github.com/nuxt/nuxt/blob/v3.15.4/package.json
  mobile:
    "@capacitor/preferences": "6.0.3" # https://github.com/ionic-team/capacitor-plugins/blob/main/preferences/package.json
    # keep 8.4.2 until fix https://github.com/ionic-team/ionic-framework/issues/30206
    "@ionic/core": "8.4.2" # by @ionic/vue, need types
    "@ionic/vue-router": "8.4.2" # https://github.com/ionic-team/ionic-framework/releases
    "@ionic/vue": "8.4.2"
    "@nuxtjs/ionic": "0.16.0" # https://github.com/nuxt-modules/ionic
    "ionicons": "7.4.0" # by @ionic/vue
