## https://pnpm.io/workspaces
packages:
  - 'layers/*'
#  - 'starts/*'

## https://pnpm.io/catalogs
## https://github.com/nuxt/nuxt/blob/v3.13.2/package.json
catalogs:
  manage:
    "@changesets/cli": "2.27.8"
    "pnpm-hoist-layer": "1.1.5"
    "rimraf": "6.0.1"
    "taze": "0.17.2"
  common:
    "@vueuse/core": "11.1.0"
    "@vueuse/nuxt": "11.1.0"
    "vue": "3.5.10"
  commonDev:
    "@iconify-json/mdi": "1.2.0"
    "@nuxt/eslint": "0.5.7"
    "@nuxt/test-utils": "3.14.2"
    "@unocss/core": "0.63.2"
    "@unocss/nuxt": "0.63.2"
    "@unocss/preset-icons": "0.63.2"
    "@unocss/preset-wind": "0.63.2"
    "@vue/test-utils": "2.4.6"
    "eslint": "9.11.1"
    "happy-dom": "15.7.4"
    "nuxt": "3.13.2"
    "typescript": "5.6.2"
    "unocss": "0.63.2"
    "vite-plugin-eslint2": "4.4.2"
    "vitest": "2.1.2"
    "vue-tsc": "2.1.6"
  mobile:
    "@capacitor/preferences": "6.0.2"
    "@ionic/vue": "8.3.2"
    "@ionic/vue-router": "8.3.2"
    "ionicons": "7.4.0"
  mobileDev:
    "@nuxtjs/ionic": "0.15.1"

