name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release to Npmjs
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout ${{ github.ref_name }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        name: Cache pnpm store
        id: cache-sdk-repo
        with:
          path: |
            ~/.asdf/
            ~/.local/share/pnpm/store/
          key: asdf-store-${{ runner.os }}

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3
        with:
          skip_install: ${{ steps.cache-sdk-repo.outputs.cache-hit == 'true' }}

      - name: Install Dependencies
        run: |
          chmod a+x .changeset/bump-top.sh
          echo "install pnpm-hoist-layer to devDep"
          pnpm -w i --no-frozen-lockfile --ignore-pnpmfile
          echo "reset the ci lockfile"
          git restore pnpm-lock.yaml
          echo "install all deps by lockfile"
          pnpm -r i --frozen-lockfile

          echo "Packaging Envs:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- node: $(node -v)" >> $GITHUB_STEP_SUMMARY
          echo "- pnpm: $(pnpm -v)" >> $GITHUB_STEP_SUMMARY
          echo "- revi: $(jq -r '.version' package.json)" >> $GITHUB_STEP_SUMMARY

      - name: Testing
        run: |
          pnpm dev:test

      - name: 'Common Coverage'
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          name: 'Common'
          working-directory: './layers/common'
      - name: 'Mobile Coverage'
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2
        with:
          name: 'Mobile'
          working-directory: './layers/mobile'

      - name: Bumping or Release
        id: changesets
        uses: changesets/action@v1
        with:
          commit: ":bookmark: bumping versions"
          title: ":rocket: release versions"
          version: .changeset/bump-top.sh
          publish: pnpm ver:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publishing Report
        run: |
          echo "Publish Result:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Published: ${{ steps.changesets.outputs.published }}" >> $GITHUB_STEP_SUMMARY
          echo "- Has Changesets: ${{ steps.changesets.outputs.hasChangesets }}" >> $GITHUB_STEP_SUMMARY
          echo "- Pull Request Number: ${{ steps.changesets.outputs.pullRequestNumber }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

      - name: Published Package
        if: steps.changesets.outputs.published == 'true'
        run: |
          pnpm publish --access public

          echo "Published Packages:" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          publishedPackages='${{ steps.changesets.outputs.publishedPackages }}'
          name=$(jq -r '.name' package.json)
          version=$(jq -r '.version' package.json)
          echo "- Package: $name, Version: $version" >> $GITHUB_STEP_SUMMARY

          # Format published packages
          echo "$publishedPackages" | jq -c '.[]' | while read pkg; do
            name=$(echo $pkg | jq -r '.name')
            version=$(echo $pkg | jq -r '.version')
            echo "- Package: $name, Version: $version" >> $GITHUB_STEP_SUMMARY
          done
